apiVersion: apps/v1
kind: Deployment
metadata:
  name: panda-ui-deployment
  labels:
    app: panda-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panda-ui
  template:
    metadata:
      labels:
        app: panda-ui
    spec:
      containers:
      - name: panda-ui
        image: 955095959256.dkr.ecr.cn-northwest-1.amazonaws.com.cn/panda-ui:{BUILD_NUM}
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: panda-ui-service
  labels:
    app: panda-ui
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: panda-ui
  type: LoadBalancer
